### PR TITLE
Fix data-diff first line bug

### LINKED ISSUE #56: data-diff first line bug
Regarding this bug: https://github.com/ember-learn/guides-source/issues/1956

I traced this problem to this line: https://github.com/empress/ember-showdown-prism/blob/main/addon/initializers/showdown-extension.js#L89

The first line of the `codeblock` variable is already filled with rendered elements e.g. for the filename. Inserting the diff operator later into this first line will fail and produce bad HTML, see example below, the `<span>` for diff-operator `+` before the `<span>` for the filename:

URL: https://guides.emberjs.com/release/tutorial/part-2/service-injection/#toc_the-router-service
```HTML
<section aria-labelledby="toc_the-router-service">
<p>To fix our problem, we would need to do the same. Ember exposes this internal state through the <em><a href="[https://api.emberjs.com/ember/release/classes/RouterService](view-source:https://api.emberjs.com/ember/release/classes/RouterService)">router service</a></em>, which we can <em><a href="[../../../services/#toc_accessing-services](view-source:https://guides.emberjs.com/release/services/#toc_accessing-services)">inject</a></em> into our component:</p>
<span class="diff-insertion"><span class="diff-operator">+</span><div class="filename js"><div class="ribbon"></div><span>app/components/share-button.js</span><pre class="language-js line-numbers"><code class="js language-js"><span class="token keyword">import</span> <span class="token punctuation">{</span> service <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@ember/service'</span><span class="token punctuation">;</span></span>
<span class="token keyword">import</span> Component <span class="token keyword">from</span> <span class="token string">'@glimmer/component'</span><span class="token punctuation">;</span>
```

Misplaced diff operator DOM view

Misplaced diff operator Safari browser

### PR DESCRIPTION
**Pull request by fry69**
Fix #56

- diff symbol renders now inside the code block for the first line
- added example for diff on the first line
- tests desperately needed

I am happy with this so far, awaiting comments.

### CODE REVIEW

**Comment by fry69** [comment]
No clue how to fix this, I did not touch anything knowingly that could provoke an `Ember is not defined` error. Please enlighten me. 

```
Built project successfully. Stored in "/tmp/tests-dist-2023722-1936-1ggxhms.oalu".
not ok 1 Chrome 115.0 - [undefined ms] - Global error: Uncaught ReferenceError: Ember is not defined at http://localhost:7357/assets/vendor.js, line 3860
    ---
        browser log: |
            {"type":"error","text":"Uncaught ReferenceError: Ember is not defined at http://localhost:7357/assets/vendor.js, line 3860\n","testContext":{}}
```

File: addon/initializers/showdown-extension.js [hunk 1]
```diff
@@ -89,27 +111,11 @@ export function initialize(/* application */) {
           codeblock = `<div class="filename ${language}"><div class="ribbon"></div><span>${attributes['data-filename'] || ''}</span>${codeblock}</div>`;
         }
       } else {
+        // (bug?) This clause may never be reached as the assert above fires in this case?
```
Comment (mansona) [inline addon/initializers/showdown-extension.js]: I'm pretty sure that you can remove this comment 🤔 I don't know how this could be a bug

**Review by mansona — APPROVED** [review]
This is an amazing change 🎉 thanks for the change. I would love you to remove the (?bug) comment but it's not a requirement for merging 👍

File: addon/initializers/showdown-extension.js (hunk 1 above)
Comment (fry69) [reply addon/initializers/showdown-extension.js]: This else clause can never be reached as long as this assert above is there, that is the reason for my comment.

https://github.com/empress/ember-showdown-prism/blob/main/addon/initializers/showdown-extension.js#L73
```js
assert(`Language "${language}" not found. Have you configured Prism correctly?`, !language || Prism.languages[language]);
```

It triggered my inner instinct to leave a comment if I encounter dead code that I have to touch to keep it consistent overall while refactoring. I can remove this comment if so desired, of course.

Or am I totally wrong on this and `assert` does not stop execution?

Comment (mansona) [reply addon/initializers/showdown-extension.js]: that type of assert only happens in dev mode so when you're running in production you can still reach that since the assertion is essentially stripped from a build

**Comment by mansona** [comment]
@fry69 regarding the Embroider error, you can ignore it. It's because of a new embroider feature that was recently added in https://github.com/embroider-build/embroider/pull/1521

I will fix that at a later date, and it's nothing that you have done to cause that issue

File: addon/initializers/showdown-extension.js (hunk 1 above)
Comment (fry69) [reply addon/initializers/showdown-extension.js]: 💡 Thanks, will remove the comment.
